import { Info, Copy } from 'lucide-react'
import { useState, useEffect, useRef } from 'react'

interface ModelsResponse {
  models: string[]
  default: string
}

export default function YouTubeTab() {
  const [url, setUrl] = useState('')
  const [models, setModels] = useState<string[]>([])
  const [selectedModel, setSelectedModel] = useState<string>('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [transcript, setTranscript] = useState('')
  const [showCopied, setShowCopied] = useState(false)
  const transcriptRef = useRef('')

  useEffect(() => {
    fetch('/models/ytt')
      .then(res => res.json())
      .then((data: ModelsResponse) => {
        setModels(data.models)
        setSelectedModel(data.default)
      })
      .catch(console.error)
  }, [])

  const handleSubmit = () => {
    setLoading(true)
    setError('')
    transcriptRef.current = ''
    setTranscript('')

    try {
      const params = new URLSearchParams({
        url: url,
        model: selectedModel,
      })

      const eventSource = new EventSource(`/ytt?${params}`)

      eventSource.onmessage = event => {
        if (event.data === 'error') {
          setError('Transcription failed')
          eventSource.close()
          return
        }
        transcriptRef.current += event.data
        setTranscript(transcriptRef.current)
      }

      eventSource.onerror = () => {
        setError('Connection error')
        eventSource.close()
        setLoading(false)
      }

      eventSource.addEventListener('done', () => {
        eventSource.close()
        setLoading(false)
      })
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An error occurred')
      setLoading(false)
    }
  }

  const copyToClipboard = () => {
    void navigator.clipboard.writeText(transcript)
    setShowCopied(true)
    setTimeout(() => setShowCopied(false), 2000)
  }

  return (
    <div className="space-y-4 p-4">
      <p className="mb-4 text-lg text-gray-600">Generate transcripts from YouTube podcasts.</p>

      <div>
        <label className="mb-2 block text-sm font-medium">YouTube URL</label>
        <input
          type="text"
          value={url}
          onChange={e => setUrl(e.target.value)}
          placeholder="Enter YouTube URL"
          className="w-full rounded-lg border px-4 py-2"
        />
        <div className="mt-2 flex items-start space-x-2 rounded-lg bg-blue-50 p-4">
          <Info className="mt-0.5 h-5 w-5 text-blue-600" />
          <p className="text-sm text-blue-700">
            Transcripts are generated by formatting autogenerated captions
          </p>
        </div>
      </div>

      <div>
        <label className="mb-2 block text-sm font-medium">Model</label>
        <select
          value={selectedModel}
          onChange={e => setSelectedModel(e.target.value)}
          className="w-full rounded-lg border px-4 py-2"
        >
          {models.map(model => (
            <option key={model} value={model}>
              {model}
            </option>
          ))}
        </select>
      </div>

      <div className="flex justify-center">
        <button
          onClick={handleSubmit}
          disabled={loading || !url}
          className="w-1/2 rounded-lg bg-blue-600 px-4 py-2 text-white hover:bg-blue-700 disabled:bg-blue-300"
        >
          {loading ? (
            <span className="flex items-center justify-center">
              <svg className="mr-2 h-5 w-5 animate-spin" viewBox="0 0 24 24">
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                  fill="none"
                />
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                />
              </svg>
              Transcribing...
            </span>
          ) : (
            'Transcribe'
          )}
        </button>
      </div>

      {error && <div className="rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}

      {transcript && (
        <div className="mt-4 rounded-lg border p-4">
          <div className="mb-2 flex items-center justify-between">
            <h3 className="font-medium">Transcript</h3>
            <button
              onClick={() => void copyToClipboard()}
              className="relative text-gray-400 hover:text-gray-600"
              aria-label="Copy transcript"
            >
              <Copy className="h-5 w-5" />
              {showCopied && (
                <span className="absolute -top-8 -right-2 rounded bg-gray-800 px-2 py-1 text-xs text-white">
                  Copied
                </span>
              )}
            </button>
          </div>
          <div className="whitespace-pre-wrap text-gray-700">{transcript}</div>
        </div>
      )}
    </div>
  )
}
