import { Info, Copy } from 'lucide-react'
import { useState, useEffect, useRef } from 'react'
import { useForm } from 'react-hook-form'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
} from '@/components/ui/form'

interface ModelsResponse {
  models: string[]
  default: string
}

interface YouTubeFormValues {
  url: string
  model: string
}

export default function YouTubeTab() {
  const [models, setModels] = useState<string[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [transcript, setTranscript] = useState('')
  const [showCopied, setShowCopied] = useState(false)
  const transcriptRef = useRef('')

  // Create form with react-hook-form
  const form = useForm<YouTubeFormValues>({
    defaultValues: {
      url: '',
      model: '',
    },
  })

  useEffect(() => {
    fetch('/models/ytt')
      .then(res => res.json())
      .then((data: ModelsResponse) => {
        setModels(data.models)
        // Set the default model
        form.setValue('model', data.default)
      })
      .catch(console.error)
  }, [form])

  const handleSubmit = form.handleSubmit((data: YouTubeFormValues) => {
    setLoading(true)
    setError('')
    transcriptRef.current = ''
    setTranscript('')

    try {
      const params = new URLSearchParams({
        url: data.url,
        model: data.model,
      })

      const eventSource = new EventSource(`/ytt?${params}`)

      eventSource.onmessage = event => {
        if (event.data === 'error') {
          setError('Transcription failed')
          eventSource.close()
          return
        }
        transcriptRef.current += event.data
        setTranscript(transcriptRef.current)
      }

      eventSource.onerror = () => {
        setError('Connection error')
        eventSource.close()
        setLoading(false)
      }

      eventSource.addEventListener('done', () => {
        eventSource.close()
        setLoading(false)
      })
    } catch (e) {
      setError(e instanceof Error ? e.message : 'An error occurred')
      setLoading(false)
    }
  })

  const copyToClipboard = () => {
    void navigator.clipboard.writeText(transcript)
    setShowCopied(true)
    setTimeout(() => setShowCopied(false), 2000)
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>YouTube Transcription</CardTitle>
        <CardDescription>Generate transcripts from YouTube podcasts.</CardDescription>
      </CardHeader>
      <CardContent>
        <Form {...form}>
          <form onSubmit={handleSubmit} className="space-y-6">
            <FormField
              control={form.control}
              name="url"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>YouTube URL</FormLabel>
                  <FormControl>
                    <Input placeholder="Enter YouTube URL" {...field} />
                  </FormControl>
                  <FormDescription>
                    <div className="mt-2 flex items-start space-x-2 rounded-lg bg-blue-50 p-4">
                      <Info className="mt-0.5 h-5 w-5 text-blue-600" />
                      <p className="text-sm text-blue-700">
                        Transcripts are generated by formatting autogenerated captions
                      </p>
                    </div>
                  </FormDescription>
                </FormItem>
              )}
            />

            <FormField
              control={form.control}
              name="model"
              render={({ field }) => (
                <FormItem>
                  <FormLabel>Model</FormLabel>
                  <Select onValueChange={field.onChange} defaultValue={field.value}>
                    <FormControl>
                      <SelectTrigger>
                        <SelectValue placeholder="Select a model" />
                      </SelectTrigger>
                    </FormControl>
                    <SelectContent>
                      {models.map(model => (
                        <SelectItem key={model} value={model}>
                          {model}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </FormItem>
              )}
            />

            <div className="flex justify-center">
              <Button type="submit" disabled={loading || !form.watch('url')} className="w-1/2">
                {loading ? (
                  <span className="flex items-center justify-center">
                    <svg className="mr-2 h-5 w-5 animate-spin" viewBox="0 0 24 24">
                      <circle
                        className="opacity-25"
                        cx="12"
                        cy="12"
                        r="10"
                        stroke="currentColor"
                        strokeWidth="4"
                        fill="none"
                      />
                      <path
                        className="opacity-75"
                        fill="currentColor"
                        d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                      />
                    </svg>
                    Transcribing...
                  </span>
                ) : (
                  'Transcribe'
                )}
              </Button>
            </div>
          </form>
        </Form>

        {error && <div className="mt-4 rounded-lg bg-red-50 p-4 text-red-700">{error}</div>}

        {transcript && (
          <div className="mt-4 rounded-lg border p-4">
            <div className="mb-2 flex items-center justify-between">
              <h3 className="font-medium">Transcript</h3>
              <button
                onClick={() => void copyToClipboard()}
                className="relative text-gray-400 hover:text-gray-600"
                aria-label="Copy transcript"
              >
                <Copy className="h-5 w-5" />
                {showCopied && (
                  <span className="absolute -top-8 -right-2 rounded bg-gray-800 px-2 py-1 text-xs text-white">
                    Copied
                  </span>
                )}
              </button>
            </div>
            <div className="whitespace-pre-wrap text-gray-700">{transcript}</div>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
